services:
  - type: web
    name: assistant-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-YOUR-API-KEY-HERE
